# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

bikesharingweb:
  ingress:
    annotations:
      kubernetes.io/ingress.class: traefik 
    hosts:
      - bikeapp.bikesharingweb.52.152.247.195.nip.io  # Assumes deployment to the 'dev' namespace

gateway:
  ingress:
    annotations:
      kubernetes.io/ingress.class: traefik 
    hosts:
      - bikeapp.bikesharingweb.52.152.247.195.nip.io  # Assumes deployment to the 'dev' namespace